import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import path from 'node:path';
import { PRIVACY_SECTIONS, PRIVACY_LAST_UPDATED } from './privacy';

const PROJECT_ROOT = path.join(import.meta.dirname, '..', '..');

// Faz 26 Commit 3 — public/gizlilik.html is generated by
// scripts/generate-privacy-page.mjs (npm run generate:privacy) from
// PRIVACY_SECTIONS/PRIVACY_LAST_UPDATED, the same source PrivacyPolicyModal
// reads. This is a bekçi test on the checked-in output, not the generator
// itself — if the generator ever drifts from the source data (a stale
// commit, a hand-edit of the .html), this catches it.
function readGeneratedPage(): string {
  return readFileSync(path.join(PROJECT_ROOT, 'public', 'gizlilik.html'), 'utf8');
}

test('public/gizlilik.html contains every PRIVACY_SECTIONS title', () => {
  const html = readGeneratedPage();
  for (const section of PRIVACY_SECTIONS) {
    assert.ok(html.includes(section.title), `expected "${section.title}" in gizlilik.html`);
  }
});

test('public/gizlilik.html has no unresolved {{TOKEN}} placeholders', () => {
  const html = readGeneratedPage();
  assert.doesNotMatch(html, /\{\{/);
});

test('public/gizlilik.html has no <script> tags or external resource links', () => {
  const html = readGeneratedPage();
  assert.doesNotMatch(html, /<script/i);
  assert.doesNotMatch(html, /href="http/i);
});

test('public/gizlilik.html shows PRIVACY_LAST_UPDATED', () => {
  const html = readGeneratedPage();
  assert.ok(html.includes(PRIVACY_LAST_UPDATED));
});
